package io.github.katarem.katarina.model.champion;

import lombok.Data;

@Data
public class Stats {
    private Integer hp;
    private Integer hpperlevel;
    private Integer mp;
    private Integer mpperlevel;
    private Integer movespeed;
    private Integer armor;
    private Double armorperlevel;
    private Integer spellblock;
    private Double spellblockperlevel;
    private Integer attackrange;
    private Integer hpregen;
    private Double hpregenperlevel;
    private Integer mpregen;
    private Integer mpregenperlevel;
    private Integer crit;
    private Integer critperlevel;
    private Integer attackdamage;
    private Integer attackdamageperlevel;
    private Double attackspeedperlevel;
    private Double attackspeed;

    private Integer flatHPPoolMod;
    private Integer rFlatHPModPerLevel;
    private Integer flatMPPoolMod;
    private Integer rFlatMPModPerLevel;
    private Integer percentHPPoolMod;
    private Integer percentMPPoolMod;
    private Integer flatHPRegenMod;
    private Integer rFlatHPRegenModPerLevel;
    private Integer percentHPRegenMod;
    private Integer flatMPRegenMod;
    private Integer rFlatMPRegenModPerLevel;
    private Integer percentMPRegenMod;
    private Integer flatArmorMod;
    private Integer rFlatArmorModPerLevel;
    private Integer percentArmorMod;
    private Integer rFlatArmorPenetrationMod;
    private Integer rFlatArmorPenetrationModPerLevel;
    private Integer rPercentArmorPenetrationMod;
    private Integer rPercentArmorPenetrationModPerLevel;
    private Integer flatPhysicalDamageMod;
    private Integer rFlatPhysicalDamageModPerLevel;
    private Integer percentPhysicalDamageMod;
    private Integer flatMagicDamageMod;
    private Integer rFlatMagicDamageModPerLevel;
    private Integer percentMagicDamageMod;
    private Integer flatMovementSpeedMod;
    private Integer rFlatMovementSpeedModPerLevel;
    private Integer percentMovementSpeedMod;
    private Integer rPercentMovementSpeedModPerLevel;
    private Integer flatAttackSpeedMod;
    private Integer percentAttackSpeedMod;
    private Integer rPercentAttackSpeedModPerLevel;
    private Integer rFlatDodgeMod;
    private Integer rFlatDodgeModPerLevel;
    private Integer percentDodgeMod;
    private Integer flatCritChanceMod;
    private Integer rFlatCritChanceModPerLevel;
    private Integer percentCritChanceMod;
    private Integer flatCritDamageMod;
    private Integer rFlatCritDamageModPerLevel;
    private Integer percentCritDamageMod;
    private Integer flatBlockMod;
    private Integer percentBlockMod;
    private Integer flatSpellBlockMod;
    private Integer rFlatSpellBlockModPerLevel;
    private Integer percentSpellBlockMod;
    private Integer flatEXPBonus;
    private Integer percentEXPBonus;
    private Integer rPercentCooldownMod;
    private Integer rPercentCooldownModPerLevel;
    private Integer rFlatTimeDeadMod;
    private Integer rFlatTimeDeadModPerLevel;
    private Integer rPercentTimeDeadMod;
    private Integer rPercentTimeDeadModPerLevel;
    private Integer rFlatGoldPer10Mod;
    private Integer rFlatMagicPenetrationMod;
    private Integer rFlatMagicPenetrationModPerLevel;
    private Integer rPercentMagicPenetrationMod;
    private Integer rPercentMagicPenetrationModPerLevel;
    private Integer flatEnergyRegenMod;
    private Integer rFlatEnergyRegenModPerLevel;
    private Integer flatEnergyPoolMod;
    private Integer rFlatEnergyModPerLevel;
    private Integer percentLifeStealMod;
    private Integer percentSpellVampMod;

}
